name: Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 'latest'

    # Roslyn Analyzers
    - name: Run Roslyn Analyzers
      run: dotnet build --no-restore -warnaserror
