name: Documentation Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  doc-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install MkDocs
      run: pip install mkdocs

    - name: Build Documentation
      run: mkdocs build

    - name: Deploy Documentation
      run: mkdocs gh-deploy
