name: Format Check

on:
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.300'

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Generate Formatting Report
      run: dotnet format --verify-no-changes --report ./formatting-report.json

    - name: Upload Formatting Report
      uses: actions/upload-artifact@v3
      with:
        name: formatting-report
        path: ./formatting-report.json

