name: Code Style and Formatting

on:
  pull_request:
    branches:
      - main

jobs:
  style-format-check:
    name: Style and Format Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.0'

    # Format Check
    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Run Format Check
      run: dotnet format --verify-no-changes --report ./formatting-report.json

    - name: Upload Formatting Report
      uses: actions/upload-artifact@v3
      with:
        name: formatting-report
        path: ./formatting-report.json

    # StyleCop Analysis
    - name: Install StyleCop Analyzers
      run: dotnet add package StyleCop.Analyzers

    - name: Run StyleCop Analysis
      run: dotnet build --no-restore -warnaserror
