name: Code Security Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  security-check:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
