name: SOLID Principles Check

on:
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Install SOLID Ruleset Analyzer
      run: dotnet tool install --global SolidAnalyzer --version 1.0.0

    - name: Run SOLID Analysis
      run: solidanalyzer check
